In [10]:
!yolo task=segment mode=predict model=yolov8s-seg.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg' save=true

Ultralytics YOLOv8.1.6 🚀 Python-3.11.5 torch-2.1.2+cpu CPU (12th Gen Intel Core(TM) i5-12500H)
YOLOv8s-seg summary (fused): 195 layers, 11810560 parameters, 0 gradients, 42.6 GFLOPs

Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 c:\Users\Rahul\Desktop\New folder\dog.jpeg: 640x384 1 person, 1 car, 1 dog, 1 backpack, 1 handbag, 190.7ms
Speed: 9.8ms preprocess, 190.7ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 384)
Results saved to runs\segment\predict7
💡 Learn more at https://docs.ultralytics.com/modes/predict


In [11]:
from ultralytics import YOLO
from PIL import Image
model = YOLO('yolov8n.pt')
source = r"C:\Users\Rahul\Desktop\pexels-jopwell-2422290.jpg"
results = model(source)  # list of Results objects
# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    print(boxes)


image 1/1 C:\Users\Rahul\Desktop\pexels-jopwell-2422290.jpg: 480x640 5 persons, 2 chairs, 64.7ms
Speed: 4.6ms preprocess, 64.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 0.,  0.,  0.,  0.,  0., 56., 56.])
conf: tensor([0.9382, 0.9316, 0.9016, 0.8606, 0.8443, 0.3624, 0.2646])
data: tensor([[2.5692e+03, 6.1450e+02, 3.3431e+03, 1.8818e+03, 9.3816e-01, 0.0000e+00],
        [1.8646e+03, 8.3511e+02, 2.5331e+03, 2.1338e+03, 9.3156e-01, 0.0000e+00],
        [1.5432e+03, 3.9535e+02, 2.0561e+03, 1.9467e+03, 9.0164e-01, 0.0000e+00],
        [3.3721e+02, 1.2317e+02, 1.1739e+03, 2.2066e+03, 8.6062e-01, 0.0000e+00],
        [1.1653e+03, 7.6282e+02, 1.7101e+03, 2.0830e+03, 8.4432e-01, 0.0000e+00],
        [9.6678e+02, 1.0821e+03, 1.6626e+03, 2.0896e+03, 3.6243e-01, 5.6000e+01],
        [1.0035e+03, 1.4638e+03, 1.3508e+03, 2.0745e+03, 2.6461e-01, 5.6000e+01]])
id: None
is_track: False
orig_shape: (2591, 36

In [12]:
for r in results:
    print(r.boxes)  # print the Boxes object containing the detection bounding boxes

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 0.,  0.,  0.,  0.,  0., 56., 56.])
conf: tensor([0.9382, 0.9316, 0.9016, 0.8606, 0.8443, 0.3624, 0.2646])
data: tensor([[2.5692e+03, 6.1450e+02, 3.3431e+03, 1.8818e+03, 9.3816e-01, 0.0000e+00],
        [1.8646e+03, 8.3511e+02, 2.5331e+03, 2.1338e+03, 9.3156e-01, 0.0000e+00],
        [1.5432e+03, 3.9535e+02, 2.0561e+03, 1.9467e+03, 9.0164e-01, 0.0000e+00],
        [3.3721e+02, 1.2317e+02, 1.1739e+03, 2.2066e+03, 8.6062e-01, 0.0000e+00],
        [1.1653e+03, 7.6282e+02, 1.7101e+03, 2.0830e+03, 8.4432e-01, 0.0000e+00],
        [9.6678e+02, 1.0821e+03, 1.6626e+03, 2.0896e+03, 3.6243e-01, 5.6000e+01],
        [1.0035e+03, 1.4638e+03, 1.3508e+03, 2.0745e+03, 2.6461e-01, 5.6000e+01]])
id: None
is_track: False
orig_shape: (2591, 3600)
shape: torch.Size([7, 6])
xywh: tensor([[2956.1382, 1248.1453,  773.8887, 1267.2889],
        [2198.8572, 1484.4658,  668.5414, 1298.7124],
        [1799.6504, 1171.0433,  512.8403, 1551.3828

In [13]:
for r in boxes:
    # Get the class IDs tensor for this result
    class_ids = r.cls

    # Get the bounding boxes for this result
    bounding_boxes = r.xyxy

    # Filter indices where the class ID corresponds to "person"
    person_indices = (class_ids == 0).nonzero(as_tuple=True)[0]

    # Extract bounding boxes for the "person" class
    person_boxes = bounding_boxes[person_indices]

    # Print or use the bounding boxes for further processing
    print("Bounding boxes for 'person' class in result:")
    print(person_boxes)


Bounding boxes for 'person' class in result:
tensor([[2569.1938,  614.5009, 3343.0825, 1881.7898]])
Bounding boxes for 'person' class in result:
tensor([[1864.5865,  835.1097, 2533.1279, 2133.8220]])
Bounding boxes for 'person' class in result:
tensor([[1543.2302,  395.3519, 2056.0706, 1946.7347]])
Bounding boxes for 'person' class in result:
tensor([[ 337.2110,  123.1655, 1173.9465, 2206.5854]])
Bounding boxes for 'person' class in result:
tensor([[1165.3254,  762.8191, 1710.0530, 2082.9775]])
Bounding boxes for 'person' class in result:
tensor([], size=(0, 4))
Bounding boxes for 'person' class in result:
tensor([], size=(0, 4))


In [17]:
for r in boxes:
    # Get the class IDs tensor for this result
    class_ids = r.cls

    # Get the bounding boxes for this result
    bounding_boxes = r.xyxy

    # Filter indices where the class ID corresponds to "person"
    person_indices = (class_ids == 0).nonzero(as_tuple=True)[0]

    # Extract bounding boxes for the "person" class
    person_boxes = bounding_boxes[person_indices]

    # Check if there are any detections of the "person" class with proper tensor
    if person_boxes.size(0) > 0:
        # Extract the first row of the tensor with proper results
        person_box = person_boxes[0]

        # Print or use the bounding box for further processing
        print("Bounding box for 'person' class in result:")
        x1 = int(person_box[0])
        y1 = int(person_box[1])
        x2 = int(person_box[2])
        y2 = int(person_box[3])
        image = Image.open(r"C:\Users\Rahul\Desktop\pexels-jopwell-2422290.jpg")
        cropped_image = image.crop((x1,  y1,  x2, y2))
        cropped_image.show()
        
        # Further processing of the bounding box
        # Your code here



Bounding box for 'person' class in result:
Bounding box for 'person' class in result:
Bounding box for 'person' class in result:
Bounding box for 'person' class in result:
Bounding box for 'person' class in result:
